## Data Understanding
### Scraping Reviews from Google Play ▶

In [1]:
import json
from google_play_scraper import app

In [2]:
# Mendapatkan details data dari Google Play Store

bca = app('com.bca',
lang = 'en', #set bahasa english untuk deskripsi
country = 'id' #set ke negara Indonesia
)

In [3]:
json_convert = json.dumps(bca, indent=4)
print(json_convert)

{
    "title": "BCA mobile",
    "description": "Bank on the go with BCA mobile app. Conduct non-cash transactions using BCA mobile banking (m-BCA) and BCA internet banking (KlikBCA Smartphone) whenever, wherever.\r\n\r\nm-BCA Benefits\r\n1. No SIM card changes\r\nm-BCA transactions are available through all GSM operators, including Telkomsel, XL Axiata, Indosat, Axis, and Three\r\n2. Low transactions cost \r\nReduce unnecessary cost using GPRS/EDGE/3G/WIFI internet connection\r\n3. Payment Data Storage\r\nm-BCA\u2019s storage feature enables you to conduct repeat transactions without having to input the data all over again\r\n4. Transfer Data\r\nm-BCA saves your transfer activities--whether you\u2019re sending funds between BCA accounts or to other banks\u2014to a list for a time-saving and reliable banking experience\r\n5. Practical and Easy to Use\r\nRecipient company or banking code is not required for payment and transfer transactions.\r\n\r\nFor BCA mobile users with Android OS and iOS, can enjoy the latest services as follows:\r\n1. Block BCA ATM Card or BCA Credit Card facility through m-Admin menu \r\n2. BCA Credit Card Activation feature through menu m-Admin \u2192 Credit Card Activation\r\n3. BCA Credit Card PIN Make / change facility via m-Admin menu \u2192 Create / Change PIN.\r\n4. Cardless Transaction feature through Setor Tarik menu \u2192 Cash withdrawal and cash deposit. \r\n5. Transfer without hassle through QR menu \u2192 Send or receive money using QR\r\nFor the time being, Cardless Transactions can be made at these following ATMs (www.bca.co.id/ATMtanpakartu)\r\n\r\nKlikBCA \r\nEasy to access KlikBCA smartphone version smartphone https://m.klikbca.com with just one click\r\n\r\nInfo BCA \r\nLink to our corporate website https://www.bca.co.id/promo\r\n\r\nBuka Rekening Baru\r\nNow you can open bank account anywhere just with your mobile phone. What you need to do to get your bank account is only by providing e-KTP, completing the form, and doing video call with our Customer Service Officer through BCA mobile application. After you done, you\u2019ll get the success notification of your opening account; you might need to directly activate your mobile banking service (by creating PIN number for transaction) and deposit money to your account. Then you are ready to do any transaction with your BCA mobile application (m-BCA menu). You will also get KlikBCA account the day after you succeed creating your mobile banking PIN via email.\r\n\r\nInfo Saldo Flazz \r\nEasy to check balance as well as the latest 10 transaction information from Flazz card, on Android smartphone equipped with Near Field Communication (NFC) feature. \r\n\r\nFor further assistant, call halo bca at 1500888 via cellular phone\r\n\r\nEnjoy using the BCA mobile.",
    "descriptionHTML": "Bank on the go with BCA mobile app. Conduct non-cash transactions using BCA mobile banking (m-BCA) and BCA internet banking (KlikBCA Smartphone) whenever, wherever.<br><br>m-BCA Benefits<br>1. No SIM card changes<br>m-BCA transactions are available through all GSM operators, including Telkomsel, XL Axiata, Indosat, Axis, and Three<br>2. Low transactions cost <br>Reduce unnecessary cost using GPRS/EDGE/3G/WIFI internet connection<br>3. Payment Data Storage<br>m-BCA\u2019s storage feature enables you to conduct repeat transactions without having to input the data all over again<br>4. Transfer Data<br>m-BCA saves your transfer activities--whether you\u2019re sending funds between BCA accounts or to other banks\u2014to a list for a time-saving and reliable banking experience<br>5. Practical and Easy to Use<br>Recipient company or banking code is not required for payment and transfer transactions.<br><br>For BCA mobile users with Android OS and iOS, can enjoy the latest services as follows:<br>1. Block BCA ATM Card or BCA Credit Card facility through m-Admin menu <br>2. BCA Credit Card Activation feature through menu m-Admin \u2192 Credit Card Activation<br>3. BCA Credit Card PIN Make / change facility via m-Admin menu \u2192 Create / Change PIN.<br>4. Cardless Transaction feature through Setor Tarik menu \u2192 Cash withdrawal and cash deposit. <br>5. Transfer without hassle through QR menu \u2192 Send or receive money using QR<br>For the time being, Cardless Transactions can be made at these following ATMs (www.bca.co.id/ATMtanpakartu)<br><br>KlikBCA <br>Easy to access KlikBCA smartphone version smartphone https://m.klikbca.com with just one click<br><br>Info BCA <br>Link to our corporate website https://www.bca.co.id/promo<br><br>Buka Rekening Baru<br>Now you can open bank account anywhere just with your mobile phone. What you need to do to get your bank account is only by providing e-KTP, completing the form, and doing video call with our Customer Service Officer through BCA mobile application. After you done, you\u2019ll get the success notification of your opening account; you might need to directly activate your mobile banking service (by creating PIN number for transaction) and deposit money to your account. Then you are ready to do any transaction with your BCA mobile application (m-BCA menu). You will also get KlikBCA account the day after you succeed creating your mobile banking PIN via email.<br><br>Info Saldo Flazz <br>Easy to check balance as well as the latest 10 transaction information from Flazz card, on Android smartphone equipped with Near Field Communication (NFC) feature. <br><br>For further assistant, call halo bca at 1500888 via cellular phone<br><br>Enjoy using the BCA mobile.",
    "summary": "BCA mobile\nPT Bank Central Asia Tbk\nBCA banking application in your hand",
    "installs": "50,000,000+",
    "minInstalls": 50000000,
    "realInstalls": 70452215,
    "score": 4.027025,
    "ratings": 1354918,
    "reviews": 555761,
    "histogram": [
        246148,
        50382,
        55536,
        71477,
        931368
    ],
    "price": 0,
    "free": true,
    "currency": "IDR",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "PT Bank Central Asia Tbk.",
    "developerId": "9162366183828083338",
    "developerEmail": "halobca@bca.co.id",
    "developerWebsite": "http://www.bca.co.id",
    "developerAddress": null,
    "privacyPolicy": "https://www.bca.co.id/id/Syarat-dan-Ketentuan/BCA-mobile",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ggZzVVDWsTm7gSnVl8m3cNFgoeUN2r7dhAZdB8lz0d_s6ZcYOkvUQdbG3dPU5LHZnWvc",
    "headerImage": "https://play-lh.googleusercontent.com/BFEpTgsr7NoDGHj-2nFOMN2uqrbgL2j_qS4F2tuNG1IEcza4CN9zuqXvEQ2EPxKojO9s",
    "screenshots": [
        "https://play-lh.googleusercontent.com/nT1ouh9h2bqRjQHEcZ_pDN8Pb5TC3CY95B-24I0SYF69TP0IaslwBrTjpEk3wDXyZVg",
        "https://play-lh.googleusercontent.com/8TbIKDyXrTl0pBnEJJvLeSYhKbkziAiWa-52NXecECI3AUrStCKbZIbtQlF3OCJRxdc",
        "https://play-lh.googleusercontent.com/iD7G7XhR8B9Cjofk9UDhiXzGKvWF8-aVZbYPfdN-M7PeWFljbOT2WZKoW-rX_vS3Xw",
        "https://play-lh.googleusercontent.com/mSdKvNVb9_L2z6y18b9z10IO2QWjUcnL1O8Ls7nYeX6k5sW6llTpYbfZhfFZ0Vf2VEGs",
        "https://play-lh.googleusercontent.com/_-12VnA4Wlk94-YoMCTfgcOiBx9N2NapuUserELM-LCvjHnCWazKxmeFYP_xF_GLRmzz",
        "https://play-lh.googleusercontent.com/yOciqUVdTr1Xkx5BtRk_c6z2mKdKupJrCYMX4SWzziWkfHxkKnyvoOEa6CJaG6ZBmWU",
        "https://play-lh.googleusercontent.com/ou5bhiWOJv_N1JAeH2wSQ7zsJiOqgAktXfmGMxJ4CA9HW3ldKq7saHQ1R9B3UA0sGQ",
        "https://play-lh.googleusercontent.com/OmLIW_Qa5-cph35GYVDcp43kac8PgbVBMPLR-6P4_GL4WxFHG1K5pznczSUrjaZAQk4"
    ],
    "video": "https://www.youtube.com/embed/FdmGaYt5QwM?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/BFEpTgsr7NoDGHj-2nFOMN2uqrbgL2j_qS4F2tuNG1IEcza4CN9zuqXvEQ2EPxKojO9s",
    "contentRating": "Rated for 3+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 12, 2012",
    "lastUpdatedOn": "Jun 19, 2025",
    "updated": 1750372637,
    "version": "4.6.7",
    "comments": [],
    "appId": "com.bca",
    "url": "https://play.google.com/store/apps/details?id=com.bca&hl=en&gl=id"
}

In [4]:
# from typing import Any
# from google_play_scraper import Sort, reviews
# from datetime import datetime
# import json

# class DateTimeEncoder(json.JSONEncoder):
#     def default(self, obj):
#         if isinstance(obj, datetime):
#                 return obj.isoformat()
#         return super(DateTimeEncoder, self).default(obj)

# # result1, continuation_token = reviews('com.HoYoverse.Nap',
# #                                      lang='en',
# #                                      country='id',
# #                                      sort=Sort.MOST_RELEVANT,
# #                                      count=8000, #banyak rows yang ingin diambil
# #                                      filter_score_with=None)

# result2, continuation_token = reviews('com.bca',
#                                      lang='en',
#                                      country='id',
#                                      sort=Sort.NEWEST,
#                                      count=10000, #banyak rows yang ingin diambil
#                                      filter_score_with=None)

# # combined_results = result1 + result2

# result2, _ = reviews('com.bca',
#                     continuation_token=continuation_token)

# json_convert2= json.dumps(result2,indent=4, cls=DateTimeEncoder)

In [4]:
from typing import Any
from google_play_scraper import Sort, reviews
from datetime import datetime
import json

class DateTimeEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime):
                return obj.isoformat()
        return super(DateTimeEncoder, self).default(obj)

result1, continuation_token = reviews('com.bca',
                                     lang='en',
                                     country='id',
                                     sort=Sort.NEWEST,
                                     count=20, #banyak rows yang ingin diambil
                                     filter_score_with=None)

result2, continuation_token = reviews('com.bca',
                                     lang='id',
                                     country='id',
                                     sort=Sort.NEWEST,
                                     count=20, #banyak rows yang ingin diambil
                                     filter_score_with=None)

combined_results = result1 + result2

combined_results2, _ = reviews('com.bca',
                    continuation_token=continuation_token)

json_convert2= json.dumps(combined_results2,indent=4, cls=DateTimeEncoder)

In [5]:
print(json_convert2)

[
    {
        "reviewId": "5edeb36f-99dc-47b7-aebb-b6c65beb3a52",
        "userName": "iNo#188 Majenang",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjUsMPzN6GjNsvuvKm_o_g8noOISel4W6tnh5y8AaxXBJLyyulUl",
        "content": "bagus",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T12:29:07",
        "replyContent": "Terima kasih atas ulasannya. Semoga aplikasi BCA mobile semakin mempermudah transaksi perbankan Bapak/Ibu.\n\n",
        "repliedAt": "2025-06-21T12:46:24",
        "appVersion": "4.6.7"
    },
    {
        "reviewId": "ae338c90-9bb5-4777-85f3-03e6faa6a08e",
        "userName": "Wawan Cell",
        "userImage": "https://play-lh.googleusercontent.com/a/ACg8ocLs_tjjVqJzQ6Zhlvca1fmuNyIhSJGl4wVuFXlzoi64TTrLzw=mo",
        "content": "coba ada notif bca dana masuk nya berbunyi bcaaaa lebih enak",
        "score": 2,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.6",
        "at": "2025-06-21T12:09:36",
        "replyContent": "Mohon maaf atas ketidaknyamanannya. Kami sarankan Bapak/Ibu dapat melakukan pendaftaran layanan Informasi via SMS/Email di cabang dengan membawa KTP dan bukti kepemilikan rekening.",
        "repliedAt": "2025-06-21T12:54:04",
        "appVersion": "4.6.6"
    },
    {
        "reviewId": "8fa243a0-45d1-4278-b18b-4be037a8782c",
        "userName": "Hendra Tj",
        "userImage": "https://play-lh.googleusercontent.com/a/ACg8ocK7M8iAJU5z9-vgULf2_dA7FqRiPfy3JfKcYlfVUbu97D86dQ=mo",
        "content": "ok",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.6",
        "at": "2025-06-21T12:06:21",
        "replyContent": "Terima kasih atas ulasannya. Semoga aplikasi BCA mobile semakin mempermudah transaksi perbankan Bapak/Ibu.\n\n",
        "repliedAt": "2025-06-21T12:46:22",
        "appVersion": "4.6.6"
    },
    {
        "reviewId": "4ca75ccd-2581-453d-89ba-b735257b0a1c",
        "userName": "araa ara",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjXADTy4WqQG-wMr5kGMoZfJJcKR2getqXTC6udCavSGXl34KB4",
        "content": "maaf mbanking sya kenapa d blokir",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": null,
        "at": "2025-06-21T11:20:44",
        "replyContent": "Kami turut prihatin atas kendalanya. Perihal tersebut tidak dapat dipastikan namun jika m-BCA terblokir karena kesalahan memasukkan PIN sebanyak 3 kali, Bapak/Ibu dapat menghubungi layanan Halo BCA di 1500888. Untuk bebas biaya pulsa dapat download aplikasi haloBCA di App Store atau Play Store atau melalui fitur Pusat Bantuan pada myBCA mobile.",
        "repliedAt": "2025-06-21T12:45:56",
        "appVersion": null
    },
    {
        "reviewId": "a75691f7-f409-4bd4-a330-619f00af6335",
        "userName": "Ariya Arafah",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjU3QATGYpS9yrGScb_ewno6VuPkTs7W-iyTHdW4VXyQ2FaMNp0",
        "content": "\ud83d\udc4d\ud83d\udc4d\ud83d\udc4d\ud83d\udc4d\ud83d\udc4d",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T11:05:15",
        "replyContent": "Terima kasih atas ulasannya. Semoga aplikasi BCA mobile semakin mempermudah transaksi perbankan Bapak/Ibu.",
        "repliedAt": "2025-06-21T12:44:52",
        "appVersion": "4.6.7"
    },
    {
        "reviewId": "6f7bd255-bc66-4071-840b-5437bd6046b3",
        "userName": "Herpit Herpit",
        "userImage": "https://play-lh.googleusercontent.com/a/ACg8ocJKQX0--bAK_QaGwrNd68KaBmEZ8bFm-tLyUJh3Y2LJBDVdvA=mo",
        "content": "parah,1 bulan 2x potonan 40 ribu,waktu saya buka rekening cuma 14ribu,dunia akhirat gak saya ikhlasin",
        "score": 1,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.5",
        "at": "2025-06-21T10:46:07",
        "replyContent": "Mohon maaf atas ketidaknyamanannya Bapak/Ibu, dikhawatirkan utk hal tersebut dikenakan biaya administrasi yg tertagih satu kali setiap bulan (hari Jumat di Minggu ke-3), namun utk pengecekan lebih lanjut dpt menghubungi layanan Halo BCA di 1500888. Sebagai informasi utk bebas biaya pulsa dpt download aplikasi haloBCA di App Store atau Play Store.",
        "repliedAt": "2025-06-21T12:44:28",
        "appVersion": "4.6.5"
    },
    {
        "reviewId": "042961a2-8996-42f7-99a2-a6005b01d30c",
        "userName": "Decil Natal",
        "userImage": "https://play-lh.googleusercontent.com/a/ACg8ocIDSFxqFnE3FZkDIpaWJjk9zkduVOAsV3mMl7Yl57uKqPmmqA=mo",
        "content": "bagus dan baik",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": null,
        "at": "2025-06-21T10:33:31",
        "replyContent": "Terima kasih atas ulasannya. Semoga aplikasi BCA mobile semakin mempermudah transaksi perbankan Bapak/Ibu.",
        "repliedAt": "2025-06-21T12:43:33",
        "appVersion": null
    },
    {
        "reviewId": "3ea8c866-491e-4c66-bdbc-eab4bfe8545c",
        "userName": "Revasya Aljufri",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjW53nKx6Ak6Nx_HCDz4dyw1F3ZptrZ7pyo5WsKD4AMtK-zEGGHBAQ",
        "content": "ini kenapa saldo saya lenyap ya saya awal setor 100 ribu jadi 90ribu karna saldo endapan setelah itu saya pakai belanja 48500 sisa 41500 tiba\" mengurangi 31500 eh pagi saya cek lagi sisa 6.500",
        "score": 1,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T10:16:34",
        "replyContent": "Mohon maaf atas ketidaknyamanannya Bapak/Ibu, mohon dapat informasikan detail kendala yang dimaksud secara rinci agar kami informasikan lebih lanjut sesuai kebutuhan.",
        "repliedAt": "2025-06-21T12:43:17",
        "appVersion": "4.6.7"
    },
    {
        "reviewId": "bf952725-ebbf-4004-86bd-09e9ced115ce",
        "userName": "Febri Dandi",
        "userImage": "https://play-lh.googleusercontent.com/a/ACg8ocKrv_FGIfIXjbG0HVi9ZisjcJmNe9CeMDBHW5emX3TfoLx4bQ=mo",
        "content": "apk rusakkk ribett",
        "score": 1,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T09:52:07",
        "replyContent": "Mohon maaf atas ketidaknyamanan Bapak/Ibu, mohon dapat informasikan detail kendala yang dimaksud agar kami informasikan lebih lanjut sesuai kebutuhan.",
        "repliedAt": "2025-06-21T10:15:09",
        "appVersion": "4.6.7"
    },
    {
        "reviewId": "70d13384-bf36-4131-bca9-c387df4f58b6",
        "userName": "Budi R 360",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjWFbK3iu2GKSbxk8lMz66DaS4QbwGDedaYy84KWo7LpHRgw4Ok",
        "content": "Update terbaru pakai verifikasi muka selalu gagal terus duhhh malah ribet.\ud83d\ude21",
        "score": 1,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T09:47:37",
        "replyContent": "Mohon maaf atas kendalanya. Perihal tersebut mohon pastikan Bapak/Ibu berada di tempat terang, kamera terlihat jelas, posisi wajah berada dalam lingkaran dan data telah sesuai. Bapak/Ibu dapat pastikan jaringan data internet stabil dan tidak menggunakan WiFi.",
        "repliedAt": "2025-06-21T12:50:35",
        "appVersion": "4.6.7"
    },
    {
        "reviewId": "f523ccac-ad23-4177-a967-9de02c669abb",
        "userName": "Manu Laka",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjWDU7y8-fzuhvZuU48SukL_RvR8BNdWCsy7CpClybM-W_HVu_w",
        "content": "layanan nya masih tetap bagus terimakasih",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.6",
        "at": "2025-06-21T09:01:55",
        "replyContent": "Terima kasih atas saran dan ulasannya. Saran dan ulasan Bapak/Ibu akan menjadi bahan evaluasi bagi kami ke depannya untuk pengembangan aplikasi yang lebih baik.\n\n",
        "repliedAt": "2025-06-21T09:20:15",
        "appVersion": "4.6.6"
    },
    {
        "reviewId": "f5edd84f-e621-4937-9781-f3ba663469b1",
        "userName": "Hanafi",
        "userImage": "https://play-lh.googleusercontent.com/a/ACg8ocIELi0Upun3IZquEJFcceJNFWRzezfx93VIgZrvWyiiPsZpuw=mo",
        "content": "baik-baik",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.6",
        "at": "2025-06-21T08:43:24",
        "replyContent": "Terima kasih atas saran dan ulasannya. Saran dan ulasan Bapak/Ibu akan menjadi bahan evaluasi bagi kami ke depannya untuk pengembangan aplikasi yang lebih baik.\n\n",
        "repliedAt": "2025-06-21T09:20:05",
        "appVersion": "4.6.6"
    },
    {
        "reviewId": "b35fed17-d61d-49c0-a01a-552c7bee43d2",
        "userName": "Joko Pamungkas",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjVnb6bIX-sTvENje6mQkAKWEwfDpTxPrhqkQXDXvKnCJOty2Ss",
        "content": "Beberapa Hari Ini Saya Mau Login kok Gk Biasa, Ada Notif Untuk Kirim Pesan,Tapi SetiapKali Ngirim Gagal Terus.",
        "score": 1,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T08:16:58",
        "replyContent": "Mohon maaf atas ketidaknyamanan Bapak/Ibu, untuk kendala tersebut mohon dapat menginformasikan detail gambar kendala yang dialami ke layanan X (Twitter) @HaloBCA atau Email halobca@bca.co.id atau Halo BCA Chat: akses melalui www.bca.co.id atau WhatsApp BCA 08111500998 agar dibantu lebih lanjut.",
        "repliedAt": "2025-06-21T09:19:53",
        "appVersion": "4.6.7"
    },
    {
        "reviewId": "ee66c4ac-5c6c-4bb9-800f-3e8cd797df4e",
        "userName": "Serba serbi kehidupan",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjUud2fny69ZolVN7khGvhSbfbPQ1TU8glQl8OELq67PwhtXACI",
        "content": "Selamat pagi ,Kenapa akhir\"ini banyak sekali nomer yg tlp ke saya mengatasnamakan BCA jakarta ,dengan menawarkan dana dan kartu debit pdhl saya sudah berkali kali menolak tapi besoknya di tlp lagi dan seminggu ini sudah ada sekitar 4 nomer berbeda yg tlp,saya merasa terintimidasi dengan kejadian ini.tolong untuk privasi pengguna mnbanking lebih diperketat lagi",
        "score": 3,
        "thumbsUpCount": 17,
        "reviewCreatedVersion": "4.6.4",
        "at": "2025-06-21T07:40:38",
        "replyContent": "Mohon maaf atas kendala yang Bapak/Ibu alami, kami sarankan untuk pengecekan lebih lanjut dapat menghubungi layanan Halo BCA di 1500888. Sebagai informasi untuk bebas biaya pulsa dapat download aplikasi haloBCA di App Store atau Play Store atau melalui fitur Pusat Bantuan pada myBCA mobile.",
        "repliedAt": "2025-06-21T09:19:11",
        "appVersion": "4.6.4"
    },
    {
        "reviewId": "d2cac941-30ff-4cdb-ba22-958c4a1bc835",
        "userName": "Yogi Sinaga",
        "userImage": "https://play-lh.googleusercontent.com/a/ACg8ocLAdYs3PX9UAxecQVGsauliWOZnvNZVEH97ugBOUVBVOwMyXg=mo",
        "content": "biaya bulanan rek atau ATM tdk bisa di liat di mutasi rek maen potong aja",
        "score": 2,
        "thumbsUpCount": 2,
        "reviewCreatedVersion": "4.6.6",
        "at": "2025-06-21T07:18:50",
        "replyContent": "Mohon maaf atas ketidaknyamanannya. Pada umumnya biaya administrasi bulanan dapat terlihat pada mutasi rekening namun apabila selisih saldo sebesar Rp50.000,- pada mutasi Bpk/Ibu disebabkan adanya ketentuan saldo mengendap maka saldo mengendap tidak terlihat pada saat Bpk/Ibu mlakukn pngecekn saldo sprti di mesin ATM.",
        "repliedAt": "2025-06-21T09:16:31",
        "appVersion": "4.6.6"
    },
    {
        "reviewId": "cdd464e6-7c16-413a-94bc-2f21375ef1db",
        "userName": "Herul ikhwan",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjVUEvnav3NCg5QtvN9nzRf76jYLtJWyJ1ZFddyoXWduuvB8jw8",
        "content": "lumayan",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": null,
        "at": "2025-06-21T06:35:05",
        "replyContent": "Terima kasih atas saran dan ulasannya. Saran dan ulasan Bapak/Ibu akan menjadi bahan evaluasi bagi kami ke depannya untuk pengembangan aplikasi yang lebih baik.\n\n",
        "repliedAt": "2025-06-21T09:07:47",
        "appVersion": null
    },
    {
        "reviewId": "04826c6b-3577-4b40-bb19-c4cc9903e162",
        "userName": "Nadir Nadir",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjX6qMCHdVi0n3-QwV7VSlkriI2mnD0Tp5uth0x-0t8EzCY0PCPc",
        "content": "Kurang memuaskan aplikasi BCA Mobile error",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T06:01:54",
        "replyContent": "Mohon maaf atas ketidaknyamanan Bapak/Ibu, mohon dapat informasikan detail kendala yang dimaksud agar kami informasikan lebih lanjut sesuai kebutuhan.",
        "repliedAt": "2025-06-21T09:07:40",
        "appVersion": "4.6.7"
    },
    {
        "reviewId": "0e26c5ba-8a70-4ea0-a067-cf3ad6c38a2f",
        "userName": "Ahmad Ghozali",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjUiRU4Y-OI0miKPiqEpiIXzRstC6CsRSuUr7Xv2H0AuuNIVrQ4",
        "content": "sangat memuaskan kunsumen",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T06:01:54",
        "replyContent": "Terima kasih atas ulasannya. Semoga aplikasi BCA mobile semakin mempermudah transaksi perbankan Bapak/Ibu.\n\n",
        "repliedAt": "2025-06-21T09:07:27",
        "appVersion": "4.6.7"
    },
    {
        "reviewId": "a09e5611-1e8e-4b4f-89b6-d82e9574e951",
        "userName": "Agung Wijaksono",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjXg4W36k31Zdx1g3mhk92cLqqssDPm4iBo6KN1GKx8oOyxipVvs",
        "content": "tampilan UI nya di update dong biar lebih menarik",
        "score": 4,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T05:59:42",
        "replyContent": "Terima kasih atas saran dan ulasannya. Saran dan ulasan Bapak/Ibu akan menjadi bahan evaluasi bagi kami ke depannya untuk pengembangan aplikasi yang lebih baik.",
        "repliedAt": "2025-06-21T09:07:20",
        "appVersion": "4.6.7"
    },
    {
        "reviewId": "c6e3aabd-d6b8-4cb9-8e7b-2575e5d7a8e8",
        "userName": "Rohman Eni",
        "userImage": "https://play-lh.googleusercontent.com/a-/ALV-UjW733JCcCAmAPE6l10v1QsGeeFd3Xl7beVJXgxf4RePm9TO9mYm",
        "content": "sangat membantu, mantaap...",
        "score": 5,
        "thumbsUpCount": 0,
        "reviewCreatedVersion": "4.6.7",
        "at": "2025-06-21T04:17:00",
        "replyContent": "Terima kasih atas ulasannya. Semoga aplikasi BCA mobile semakin mempermudah transaksi perbankan Bapak/Ibu.\n\n",
        "repliedAt": "2025-06-21T09:06:44",
        "appVersion": "4.6.7"
    }
]

#### Load to Pandas

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame(np.array(combined_results), columns=['review'])
df = df.join(pd.DataFrame(df.pop('review').tolist()))
df.head(5)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,cced94d5-3c46-4332-9465-78d2a8d6cdf0,Mokondo,https://play-lh.googleusercontent.com/a/ACg8oc...,"mau verifikasi aja sulit, kirim kode otp tp ga...",1,0,None,2025-06-21 16:18:49,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, apa...",2025-06-21 17:00:15,None
1,2deacb07-7baf-4b93-874d-70437ccbe2d5,Jermy Patrick,https://play-lh.googleusercontent.com/a-/ALV-U...,sejauh ini aplikasi berjalan lancar,5,0,4.6.6,2025-06-21 11:52:54,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-21 12:46:18,4.6.6
2,5c18a034-3bb1-499f-8a53-8dbc660dec15,Boyke Sihombing,https://play-lh.googleusercontent.com/a-/ALV-U...,Good!,5,0,4.6.4,2025-06-21 10:39:59,Thank you for the review. Hopefully the BCA mo...,2025-06-21 12:43:43,4.6.4
3,735dc7e2-d56e-4489-a2b3-cf7dd9cc8488,samudra arenza,https://play-lh.googleusercontent.com/a-/ALV-U...,"hi, since 19 June 2025, some how this app alwa...",1,0,4.2.4,2025-06-20 07:08:33,We apologize for the inconvenience Sir/Madam h...,2025-06-20 08:33:30,4.2.4
4,d048c492-7df3-4165-b69c-434622f7d9aa,Henz Tan,https://play-lh.googleusercontent.com/a-/ALV-U...,"kenapa app nya gak bsa dibuka ya? ""This site c...",4,0,None,2025-06-20 05:58:20,Mohon maaf atas kendala yang Bapak/Ibu alami. ...,2025-06-20 08:26:05,None

In [8]:
# sort berdasarkan tanggal

df = df.sort_values(by='at', ascending=False)
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
20,c2c9b21f-8d61-4087-92dc-4aba2f94d606,Fandi Hardian,https://play-lh.googleusercontent.com/a/ACg8oc...,cocok dengan aplikasi ini buat tranfer ringan ...,5,0,4.6.7,2025-06-21 22:04:56,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-21 23:01:50,4.6.7
21,dbef35c0-abf0-423e-bf99-2d3fb91ece44,Hanan Mashuri,https://play-lh.googleusercontent.com/a-/ALV-U...,Mohon perbaiki sistem dan bug apk nya di tungg...,1,0,None,2025-06-21 22:03:30,Mohon maaf atas ketidaknyamanannya. Saran dan ...,2025-06-22 09:59:55,None
22,a10a9792-ed75-4e2c-b4e4-127fa4541115,Buhori Fika,https://play-lh.googleusercontent.com/a/ACg8oc...,mantaaaap,5,0,4.6.6,2025-06-21 21:10:23,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-21 21:31:28,4.6.6
23,e6614fea-db98-476c-9470-6562a41f6505,Nani Banny,https://play-lh.googleusercontent.com/a-/ALV-U...,sangat membantu,5,0,4.6.7,2025-06-21 20:59:50,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-21 21:01:30,4.6.7
24,9c01e828-1590-4fa3-bbe1-1b2bc95ee407,Well done,https://play-lh.googleusercontent.com/a/ACg8oc...,mengapa sya mau masuk gbisa bisa..,5,0,4.6.7,2025-06-21 20:48:36,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2025-06-21 21:06:03,4.6.7
25,7317ffb0-99e0-462b-afd5-791316e91d48,Anak Bontot,https://play-lh.googleusercontent.com/a-/ALV-U...,TOLONG POTONGAN BULANANNYA 🙏 Saya Suka bank BC...,3,0,4.6.7,2025-06-21 20:46:11,"Terima kasih atas saran yang diberikan, untuk ...",2025-06-21 22:00:50,4.6.7
26,5815874f-6cf8-46d6-87ab-92f03e38eb16,Herman abid,https://play-lh.googleusercontent.com/a/ACg8oc...,pokoknya BCA tetap oke jooz🤝👍,5,0,4.6.6,2025-06-21 20:01:52,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-21 21:02:18,4.6.6
27,b47117dc-8274-46e8-8ea8-543552826fc2,IKBAL SUHENDAR,https://play-lh.googleusercontent.com/a-/ALV-U...,uang gua tiba tiba ilang,1,0,4.6.6,2025-06-21 19:46:19,Mohon maaf atas ketidaknyamanannya. Jika saldo...,2025-06-21 19:50:51,4.6.6
28,a03a8cd3-5c13-40bc-926c-95249fe133f6,Edi Supriyadi,https://play-lh.googleusercontent.com/a-/ALV-U...,bca mobil saya kok tidak ada Publik/Utiliti di...,4,0,4.6.7,2025-06-21 19:02:02,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2025-06-22 10:04:39,4.6.7
29,6f7d5152-c02b-4828-a760-1ab3c87be57d,agus satriyadi,https://play-lh.googleusercontent.com/a-/ALV-U...,semoga UI nya bisa lebih baik lagi 🙏 . rate bi...,4,0,4.6.7,2025-06-21 18:52:56,"Terima kasih atas ulasannya, hal ini menjadi m...",2025-06-22 09:59:22,4.6.7
30,eed20367-dd94-446b-b0f3-9ecf50b24967,Joni Aliong,https://play-lh.googleusercontent.com/a-/ALV-U...,maaf kenapa sy tidak bisa cardless (transaksi ...,1,2,4.6.7,2025-06-21 18:45:10,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, moh...",2025-06-22 10:06:47,4.6.7
31,ed4c4cfb-a55c-49cb-86ab-7dab2453dca2,monyet tampan,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus,5,0,4.6.6,2025-06-21 18:39:56,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-21 19:12:43,4.6.6
32,82458fa9-4470-41bd-83a7-b475898c7ce3,Meriati Chen,https://play-lh.googleusercontent.com/a/ACg8oc...,tidak bisa pake,1,0,None,2025-06-21 17:06:07,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2025-06-21 17:31:29,None
33,59b3fe0c-e130-40f6-aca8-ab4445ef4421,Beny Resza,https://play-lh.googleusercontent.com/a-/ALV-U...,padahal sudah masuk'n nomer kartu ATM habis it...,1,0,None,2025-06-21 17:01:58,Mohon maaf atas kendala yang Bapak/Ibu alami. ...,2025-06-21 17:41:27,None
0,cced94d5-3c46-4332-9465-78d2a8d6cdf0,Mokondo,https://play-lh.googleusercontent.com/a/ACg8oc...,"mau verifikasi aja sulit, kirim kode otp tp ga...",1,0,None,2025-06-21 16:18:49,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, apa...",2025-06-21 17:00:15,None
34,d64d070e-8013-469f-831c-bb0cb50c789c,hendra hoerudin,https://play-lh.googleusercontent.com/a/ACg8oc...,setiap ada yang TF selalu dipotong 18rb atow 2...,2,0,4.6.6,2025-06-21 16:12:59,Mohon maaf atas ketidaknyamanannya Bpk/Ibu. Se...,2025-06-21 16:55:23,4.6.6
35,a8058146-01b2-4e55-96a0-ba51587929a7,Abie Sufyan,https://play-lh.googleusercontent.com/a-/ALV-U...,Lumayan lah,4,0,4.6.7,2025-06-21 15:41:56,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-21 16:04:42,4.6.7
36,c7164bc0-0b64-4dff-8aa6-34ad6b2e60ec,Akhsan Arrafff,https://play-lh.googleusercontent.com/a-/ALV-U...,👍👍👍👍👍,5,0,None,2025-06-21 14:25:37,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-21 14:50:28,None
37,a4e73d19-9dbc-41bb-ab10-2015c894fa78,Yanto Yanti,https://play-lh.googleusercontent.com/a/ACg8oc...,ok,5,0,4.6.7,2025-06-21 14:01:30,Thank you for the review. Hopefully the BCA mo...,2025-06-21 14:15:49,4.6.7
38,1964fd03-343d-4d0a-ac3f-7ee679a52be8,Juniarto Grab,https://play-lh.googleusercontent.com/a/ACg8oc...,good job,5,0,4.6.7,2025-06-21 13:36:48,Thank you for the review. Hopefully the BCA mo...,2025-06-21 14:15:37,4.6.7
39,52c663e6-a6fa-44f2-a3fa-d76ffeb0e9c3,Fitri Nirmala,https://play-lh.googleusercontent.com/a/ACg8oc...,Saya pengguna BCA Tahapan Xpresi merasa kebera...,4,0,4.6.7,2025-06-21 13:34:07,"Mohon maaf atas ketidaknyamanannya, ulasan Bap...",2025-06-21 14:14:59,4.6.7
1,2deacb07-7baf-4b93-874d-70437ccbe2d5,Jermy Patrick,https://play-lh.googleusercontent.com/a-/ALV-U...,sejauh ini aplikasi berjalan lancar,5,0,4.6.6,2025-06-21 11:52:54,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-21 12:46:18,4.6.6
2,5c18a034-3bb1-499f-8a53-8dbc660dec15,Boyke Sihombing,https://play-lh.googleusercontent.com/a-/ALV-U...,Good!,5,0,4.6.4,2025-06-21 10:39:59,Thank you for the review. Hopefully the BCA mo...,2025-06-21 12:43:43,4.6.4
3,735dc7e2-d56e-4489-a2b3-cf7dd9cc8488,samudra arenza,https://play-lh.googleusercontent.com/a-/ALV-U...,"hi, since 19 June 2025, some how this app alwa...",1,0,4.2.4,2025-06-20 07:08:33,We apologize for the inconvenience Sir/Madam h...,2025-06-20 08:33:30,4.2.4
4,d048c492-7df3-4165-b69c-434622f7d9aa,Henz Tan,https://play-lh.googleusercontent.com/a-/ALV-U...,"kenapa app nya gak bsa dibuka ya? ""This site c...",4,0,None,2025-06-20 05:58:20,Mohon maaf atas kendala yang Bapak/Ibu alami. ...,2025-06-20 08:26:05,None
5,f3b60e32-ef55-4a4c-bb34-23655a7217cb,Gedhibal 27 Comedy,https://play-lh.googleusercontent.com/a-/ALV-U...,akan sangat membantu jika ada fitur update sal...,4,0,4.6.6,2025-06-19 15:04:14,"Mohon maaf atas ketidaknyamanannya, apabila ya...",2025-06-19 15:06:23,4.6.6
6,afc32860-d60b-4b72-b021-b44cc60b5b59,Aldrin Zwain,https://play-lh.googleusercontent.com/a-/ALV-U...,The OTP code was never sent to me even after t...,1,0,4.6.6,2025-06-19 12:01:29,"Sorry for the inconvenience, for SMS receiving...",2025-06-19 13:30:09,4.6.6
7,ed512b44-0bfe-4f21-990a-68b487ad9fcf,jaenal leegenmao,https://play-lh.googleusercontent.com/a-/ALV-U...,"26 Juni update app gak bisa buka, auto close S...",5,1,4.6.6,2025-06-19 03:32:53,Terima kasih atas ulasannya. Semoga fasilitas ...,2025-06-19 09:02:16,4.6.6
8,b38f1c61-b3b0-487f-b1a8-1b6ada63a4c4,Bambang Hermawan,https://play-lh.googleusercontent.com/a-/ALV-U...,BCA mobile mau minta berapa kali verifikasi? g...,1,1,4.6.6,2025-06-18 11:24:57,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2025-06-18 12:20:30,4.6.6
9,5bc398b2-51ac-42c9-9c87-dbcbfc3536d6,Diana Putri,https://play-lh.googleusercontent.com/a/ACg8oc...,ini kenapa internet terputus terus,1,0,4.6.6,2025-06-18 10:28:02,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, dik...",2025-06-18 10:58:37,4.6.6
10,2316f7d7-530c-42ad-897c-a56adfa0594f,DAENG SARA,https://play-lh.googleusercontent.com/a-/ALV-U...,semoga kedepannya login aplikasi bisa mengguna...,1,0,4.6.5,2025-06-18 10:11:50,Mohon maaf atas ketidaknyamanannya. Saran dan ...,2025-06-18 10:24:20,4.6.5
11,cab73b2b-5693-4efb-b98c-bbece537ec4f,Abiem Syaaban Sahriansyah,https://play-lh.googleusercontent.com/a-/ALV-U...,ayolah bca masa iya aku hubungin cs gabisa mal...,2,0,4.6.6,2025-06-18 09:58:49,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, jik...",2025-06-18 10:26:07,4.6.6
12,ee17f2f6-ebad-44af-8def-eb2cfaec920d,Muhammad Septiandi,https://play-lh.googleusercontent.com/a-/ALV-U...,Very good,5,1,4.6.4,2025-06-17 13:48:02,Thank you for the review. Hopefully the BCA mo...,2025-06-17 14:10:22,4.6.4
13,7efd67c3-a3c6-4234-9d78-097d08d847c5,Dixon,https://play-lh.googleusercontent.com/a/ACg8oc...,jelek,1,0,4.6.6,2025-06-17 09:14:24,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, moh...",2025-06-17 10:00:03,4.6.6
14,3f610752-e06d-412a-972e-c1e8c8201466,Kevin Moses,https://play-lh.googleusercontent.com/a-/ALV-U...,"So uh, why is the app suddenly taking so much ...",2,0,4.6.6,2025-06-16 22:34:35,We apologize for the problems you are experien...,2025-06-16 23:22:32,4.6.6
15,7f58de7b-2c16-478c-8eaa-04cb92a626bd,Rizal Satria Darmawan,https://play-lh.googleusercontent.com/a-/ALV-U...,DONE!! Already fixed... BCA saya tidak bisa ba...,3,0,4.6.6,2025-06-16 09:41:21,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, dik...",2025-06-16 10:02:14,4.6.6
16,455e387d-f088-4aaf-9d13-ecf72950f4c0,Bima Septianto,https://play-lh.googleusercontent.com/a-/ALV-U...,Good 👍,5,0,4.6.6,2025-06-16 01:47:14,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-06-16 01:58:17,4.6.6
17,f778d1f6-3a51-4c99-adbc-2a8a821fd793,Yahya,https://play-lh.googleusercontent.com/a/ACg8oc...,unreliable!,1,0,4.6.6,2025-06-15 03:14:40,Sorry for the inconvenience. Your suggestions ...,2025-06-15 09:11:07,4.6.6
18,8b67f9fd-db05-4c9f-b45d-637458b6c4e1,Shaprich Kuwera,https://play-lh.googleusercontent.com/a/ACg8oc...,kenapa tiba-tiba M-Bca Saya terblokir????,5,0,4.6.4,2025-06-13 18:36:40,"Mohon maaf atas kendala yang Bapak/Ibu alami, ...",2025-06-13 19:35:18,4.6.4
19,cfda8022-30b8-4796-8d07-a8427d4bde5f,Dodik Ridwan,https://play-lh.googleusercontent.com/a-/ALV-U...,Stuck.,1,0,4.6.6,2025-06-12 20:46:29,"We apologize for the inconvenience, please pro...",2025-06-12 20:53:02,4.6.6

In [9]:
df.shape

(40, 11)

In [10]:
df = df['content']
df.head(10)

20    cocok dengan aplikasi ini buat tranfer ringan ...
21    Mohon perbaiki sistem dan bug apk nya di tungg...
22                                            mantaaaap
23                                      sangat membantu
24                   mengapa sya mau masuk gbisa bisa..
25    TOLONG POTONGAN BULANANNYA 🙏 Saya Suka bank BC...
26                        pokoknya BCA tetap oke jooz🤝👍
27                             uang gua tiba tiba ilang
28    bca mobil saya kok tidak ada Publik/Utiliti di...
29    semoga UI nya bisa lebih baik lagi 🙏 . rate bi...
Name: content, dtype: object

In [11]:
# save to CSV
df.to_csv('bca_new_data.csv', index=False)